name: saf_stream
description: Read and write Android SAF `DocumentFile`.
version: 0.11.3
homepage: https://github.com/flutter-cavalry/saf_stream

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.fluttercavalry.saf_stream
        pluginClass: SafStreamPlugin
